### ISSUE TITLE
FetchXML Paging

### ISSUE THREAD

**Issue by altmank** [mariusso/WebAPI.REST.js#2]
Can you recommend an approach for how to implement promise-based paging with the executeFetchXML method?

Sorry for using an issue to ask this.

**Comment by mariusso** [comment]
I haven't built in any good paging support  in the fetchXml-method. However. You can still use paging and/or a paging cookie. These are set in the fetchXML itself and not in the request itself.

See these articles for details:

https://msdn.microsoft.com/nb-no/library/mt607533.aspx#bkmk_useFetchXML

https://msdn.microsoft.com/nb-no/library/gg309717.aspx
