### ISSUE TITLE
How do I use the asynchronous option?

### ISSUE THREAD

**Issue by drt0927** [mariusso/WebAPI.REST.js#5]
webAPI.REST.retrieveMultiple(
	            		"systemusers",
						"?$select=_businessunitid_value,systemuserid,fullname" +
						"&$filter=fullname ne 'INTEGRATION' and fullname ne 'SYSTEM'")
						
						.then(function(res){
							// code...
						})
						
						.catch(function(err){
							// code..
						});

How do I use the asynchronous option?

**Comment by mariusso** [comment]
That example is asynchronous . The "then"-function will execute when the request is complete.

**Comment by mariusso** [comment]
Sorry. It's like this: webAPI.REST.retrieveMultiple("systemusers",
"?$select=_businessunitid_value,systemuserid,fullname" +
"&$filter=fullname ne 'INTEGRATION' and fullname ne 'SYSTEM'").then(function(res){ *Code goes here* });
